CREATE TABLE banners(
    id BINARY(16) NOT NULL,
    name TINYTEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT '1970-01-01 00:00:01',
    PRIMARY KEY (id),
    UNIQUE (name)
);