stages:
  - build

lint-and-test:
  stage: build
  image: $DOCKER_REGISTRY_PULL/rust-builder
  before_script:
    - git config --global url."https://gitlab+deploy-token-2:${OCR_DEPLOY_TOKEN_PASSWORD}@code.ex.c-lab.ee/open-cyber-range/public/sdl-parser.git/".insteadOf "ssh://git@code.ex.c-lab.ee/open-cyber-range/public/sdl-parser"
    - git clone https://gitlab+deploy-token-2:${OCR_DEPLOY_TOKEN_PASSWORD}@code.ex.c-lab.ee/open-cyber-range/public/sdl-parser.git
  script:
    - cargo clippy -- -Dwarnings
    - cargo build --verbose
  only:
    - develop
    - master
    - merge_requests
