stages:
  - build

lint-and-test:
  stage: build
  image: $DOCKER_REGISTRY_PULL/rust-builder
  script:
    - cargo clippy -- -Dwarnings
    - cargo build --verbose
  only:
    - develop
    - master
    - merge_requests
