stages:
  - build

lint-and-test:
  stage: build
  image: $DOCKER_REGISTRY_PULL/rust-builder
  before_script:
    - sed -i 's/ssh:\/\/git@/https:\/\/gitlab-ci-token:${CI_JOB_TOKEN}@/ranger' ranger/Cargo.toml
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@code.ex.c-lab.ee/public/ranger/sdl-parser.git/".insteadOf "git@code.ex.c-lab.ee:open-cyber-range/public/ranger/sdl-parser.git"
    - git clone git@code.ex.c-lab.ee:open-cyber-range/public/sdl-parser.git
    - git submodule sync && git submodule update --init
  script:
    - cargo clippy -- -Dwarnings
    - cargo build --verbose
  only:
    - develop
    - master
    - merge_requests
