host: ranger
port: 8085
deployers:
  my-machiner-deployer: http://ranger-vmware-machiner:9999
  my-switch-deployer: http://ranger-vmware-switcher:9998
  my-template-deployer: http://ranger-vmware-templater:9997
  real-machiner-deployer: http://real-ranger-vmware-machiner:10002
  real-switch-deployer: http://real-ranger-vmware-switcher:10003
  real-template-deployer: http://real-ranger-vmware-templater:10001
  real-executor-deployer: http://real-ranger-vmware-executor:10004

default_deployment_group: real-deal-deployment-group
deployment_groups:
  test-deployment-group:
    - my-machiner-deployer
    - my-switch-deployer
    - my-template-deployer
  real-deal-deployment-group:
    - real-machiner-deployer
    - real-switch-deployer
    - real-template-deployer
    - real-executor-deployer
database_url: mysql://mysql_user:mysql_pass@mariadb:3306/ranger
