CREATE TABLE exercises (
    id BINARY(16) NOT NULL,
    name TINYTEXT NOT NULL,
    sdl_schema LONGTEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
    PRIMARY KEY (id),
    UNIQUE (name, deleted_at)
);