version: '3'

services:
  ranger:
    image: nexus.ex.c-lab.ee:8003/rust-development:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    user: vscode

  ranger-vmware-machiner:
    image: nexus.ex.c-lab.ee:8003/ranger-vmware-machiner:latest
    volumes:
      - ./configs/ranger-vmware-machiner.yml:/etc/opt/ranger/ranger-vmware-machiner/config.yml
    ports:
      - "9999:9999"
    restart: unless-stopped

  ranger-vmware-switcher:
    image: nexus.ex.c-lab.ee:8003/ranger-vmware-switcher:latest
    volumes:
      - ./configs/ranger-vmware-switcher.yml:/etc/opt/ranger/ranger-vmware-switcher/config.yml
    ports:
      - "9998:9998"
    restart: unless-stopped
