version: '3'

services:
  ranger:
    image: nexus.ex.c-lab.ee:8002/rust-development:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    network_mode: service:ranger-vmware-node-deployer
    user: vscode

  ranger-vmware-node-deployer:
    image: nexus.ex.c-lab.ee:8002/ranger-vmware-node-deployer:latest
    volumes:
      - ./configs/ranger-vmware-node-deployer.yml:/etc/opt/ranger/ranger-vmware-node-deployer/config.yml
    ports:
      - "9999:9999"
    restart: unless-stopped
