[registries]
main-registry = { index = "http://deputy-package-server-repository-combo/git/index.git", api = "http://deputy-package-server-repository-combo:8080/" }

[package]
index_path = "/home/vscode/.deputy/index"
download_path = "/home/vscode/.deputy/download"
