[package]
name = "ranger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.deb]
name = "ranger"
maintainer = "Madis-Mikk Remmet <madismikk.remmet@c14.ee>"
copyright = "2022, CR14 <info@cr14.ee>"
depends = "$auto, systemd"
section = "utility"
priority = "optional"
assets = [
  [
    "target/release/ranger",
    "/var/opt/ranger/bin/",
    "755",
  ],
  [
    "assets/default-production-config.yml",
    "/etc/opt/ranger/ranger/config.yml",
    "644",
  ],
]
systemd-units = { unit-name = "ranger", unit-scripts = "assets/unit-scripts" }

[dependencies]
actix = "0.13"
actix-web = "4"
actix-http = { version = "3", features = ["http2", "ws"] }
anyhow = "1"
futures = "0.3"
insta = "1"
log = "0.4"
lazy_static = "1.4"
rand = "0.8"
ranger-grpc = { path = "../ranger-grpc" }
sdl-parser = { git = "ssh://git@code.ex.c-lab.ee/open-cyber-range/public/sdl-parser", version = "0.8", branch = "develop" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
semver = "1"
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "time",
  "fs",
  "macros",
  "net",
  "rt",
] }
tonic = "0.7"

[dev-dependencies]
actix-rt = "2"
sdl-parser = { git = "ssh://git@code.ex.c-lab.ee/open-cyber-range/public/sdl-parser", branch = "develop", features = [
  "test",
] }

[dependencies.uuid]
version = "1.1.1"
features = ["v4"]
