[package]
name = "ranger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
actix-web = "4"
anyhow = "1"
insta = "1"
log = "0.4"
rand = "0.8"
ranger-grpc = { path = "../ranger-grpc" }
sdl-parser = { git = "ssh://git@code.ex.c-lab.ee/open-cyber-range/public/sdl-parser", version = "0.8" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tempfile = "3"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "time",
  "fs",
  "macros",
  "net",
  "rt",
] }
tonic = "0.7"

[dev-dependencies]
actix-rt = "2"
sdl-parser = { git = "ssh://git@code.ex.c-lab.ee/open-cyber-range/public/sdl-parser", features = [
  "test",
] }
