[package]
name = "ranger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
anyhow = "1"
insta = "1"
ranger-grpc = { path = "../ranger-grpc" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tempfile = "3"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "time",
  "fs",
  "macros",
  "net",
] }
tonic = "0.7"
